Repository babylonlabs-io/babylon, pull requests merged in 2024-10, with the labels that each got.

#141 fix handling covent message when quorum is already reached
  CHANGELOG.md
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/keeper_test.go
  x/btcstaking/keeper/power_dist_change_test.go
Labels: bug

#144 feat: Add new external events related to finality provider status change
  CHANGELOG.md
  proto/babylon/btcstaking/v1/events.proto
  proto/babylon/btcstaking/v1/incentive.proto
  x/btcstaking/keeper/finality_providers.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/power_dist_change.go
  x/btcstaking/types/events.go
  x/btcstaking/types/events.pb.go
  x/btcstaking/types/incentive.go
  x/btcstaking/types/incentive.pb.go
  x/btcstaking/types/incentive_test.go
Labels: api breaking

#169 chore: Improve external events format
  CHANGELOG.md
  proto/babylon/btcstaking/v1/events.proto
  x/btcstaking/README.md
  x/btcstaking/keeper/power_dist_change.go
  x/btcstaking/types/events.go
  x/btcstaking/types/events.pb.go
Labels: api breaking, backport v0.12.x

#180 fix: Non-determinism in sorting finality providers in the voting power table
  CHANGELOG.md
  x/btcstaking/types/btcstaking.go
  x/btcstaking/types/btcstaking_test.go
Labels: bug, consensus breaking, backport release/v0.12.x

#185 Properly validate whether tranactions are standard
  CHANGELOG.md
  btcstaking/staking.go
  btcstaking/staking_test.go
  x/btcstaking/types/create_delegation_parser.go
  x/btcstaking/types/validate_parsed_message.go
Labels: consensus breaking, backport release/v0.12.x

#193 fix: fixing witness construction of slashing tx
  CHANGELOG.md
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/btc_delegation_test.go
  x/btcstaking/types/btc_slashing_tx.go
  x/btcstaking/types/btc_slashing_tx_test.go
  x/btcstaking/types/btc_undelegation_test.go
Labels: backport release/v0.12.x

#197 fix: `BTCDelgationResponse` missing `staking_time`
  CHANGELOG.md
  cmd/babylond/cmd/genhelpers/set_btc_delegations_test.go
  proto/babylon/btcstaking/v1/query.proto
  testutil/datagen/btcstaking.go
  x/btcstaking/keeper/grpc_query_test.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/types/btc_delegation_test.go
  x/btcstaking/types/btc_undelegation_test.go
  x/btcstaking/types/query.go
  x/btcstaking/types/query.pb.go
Labels: bug, api breaking, backport release/v0.12.x

#215 feat: Implement ADR-29 - generalized unbonding
  CHANGELOG.md
  proto/babylon/btcstaking/v1/btcstaking.proto
  proto/babylon/btcstaking/v1/events.proto
  proto/babylon/btcstaking/v1/query.proto
  proto/babylon/btcstaking/v1/tx.proto
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  test/e2e/configurer/chain/commands_btcstaking.go
  x/btcstaking/client/cli/tx.go
  x/btcstaking/keeper/bench_test.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/incentive_test.go
  x/btcstaking/keeper/keeper_test.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/keeper/power_dist_change_test.go
  x/btcstaking/keeper/voting_power_table_test.go
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/btcstaking.pb.go
  x/btcstaking/types/events.pb.go
  x/btcstaking/types/msg.go
  x/btcstaking/types/query.go
  x/btcstaking/types/query.pb.go
  x/btcstaking/types/tx.pb.go
Labels: consensus breaking, api breaking

#224 chore: Make injected checkpoint a standard tx
  CHANGELOG.md
  app/app.go
  proto/babylon/checkpointing/v1/checkpoint.proto
  x/checkpointing/proposal.go
  x/checkpointing/proposal_test.go
  x/checkpointing/types/checkpoint.pb.go
  x/checkpointing/types/codec.go
Labels: consensus breaking

#218 Fix removing voting power during expiry
  CHANGELOG.md
  testutil/helper/helper.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/genesis_test.go
  x/btcstaking/keeper/grpc_query_test.go
  x/btcstaking/keeper/inclusion_proof.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/keeper/power_dist_change_test.go
  x/btcstaking/types/validate_parsed_message.go
  x/btcstaking/types/validate_parsed_message_test.go
Labels: consensus breaking

#211 mint: Babylon inflation module
  CHANGELOG.md
  app/app.go
  app/keepers/keepers.go
  app/test_helpers.go
  app/upgrades/v1/upgrades.go
  app/upgrades/v1/upgrades_test.go
  cmd/babylond/cmd/genesis.go
  proto/babylon/mint/v1/genesis.proto
  proto/babylon/mint/v1/mint.proto
  proto/babylon/mint/v1/query.proto
  test/e2e/initialization/config.go
  wasmbinding/test/custom_query_test.go
  x/mint/README.md
  x/mint/abci.go
  x/mint/abci_test.go
  x/mint/client/cli/query.go
  x/mint/keeper/genesis.go
  x/mint/keeper/grpc_query.go
  x/mint/keeper/grpc_query_test.go
  x/mint/keeper/keeper.go
  x/mint/module.go
  x/mint/module_test.go
  x/mint/simulation/decoder.go
  x/mint/simulation/decoder_test.go
  x/mint/types/constants.go
  x/mint/types/events.go
  x/mint/types/expected_keepers.go
  x/mint/types/genesis.go
  x/mint/types/genesis.pb.go
  x/mint/types/keys.go
  x/mint/types/mint.pb.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
  x/mint/types/query.pb.go
  x/mint/types/query.pb.gw.go
Labels: consensus breaking

#238 Add more info to staking creation event
  CHANGELOG.md
  proto/babylon/btcstaking/v1/events.proto
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/events.go
  x/btcstaking/types/events.pb.go
Labels: api breaking
