Repository babylonlabs-io/babylon, pull requests merged in 2025-03, with the labels that each got.

#594 refund fee to correct receipient
  CHANGELOG.md
  x/incentive/keeper/keeper_test.go
  x/incentive/keeper/refundable_msg_index.go
Labels: consensus breaking, backport-to-release/v1.x

#604 FIx build on main
  testutil/keeper/incentive.go
  x/finality/keeper/power_dist_change_test.go
  x/incentive/keeper/genesis.go
  x/incentive/keeper/keeper.go
  x/incentive/keeper/reward_tracker_store.go
Labels: A:no-changelog

#599 Verify staker sig for unbonding tx
  CHANGELOG.md
  btcstaking/btcstaking_test.go
  proto/babylon/btcstaking/v1/tx.proto
  proto/buf.lock
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  test/e2e/configurer/chain/commands_btcstaking.go
  testutil/datagen/btc_transaction.go
  testutil/datagen/btcstaking.go
  testutil/incentives-helper/keeper.go
  x/btcstaking/client/cli/tx.go
  x/btcstaking/keeper/btc_staking_consumer_events_test.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/keeper/unbonding_transaction_sig_validation.go
  x/btcstaking/keeper/unbonding_transaction_sig_validation_test.go
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/tx.pb.go
  x/finality/keeper/msg_server_test.go
Labels: consensus breaking, api breaking, backport-to-release/v1.x

#589 chore(incentive): rename `btc_delegation` stakeholder type to `btc_staker`
  CHANGELOG.md
  docs/register-bitcoin-stake.md
  proto/babylon/incentive/genesis.proto
  proto/babylon/incentive/tx.proto
  test/e2e/btc_rewards_distribution_e2e_test.go
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  x/finality/keeper/msg_server_test.go
  x/incentive/client/cli/tx.go
  x/incentive/keeper/btc_staking_gauge_test.go
  x/incentive/keeper/grpc_query_test.go
  x/incentive/keeper/msg_server_test.go
  x/incentive/keeper/reward_gauge.go
  x/incentive/keeper/reward_gauge_test.go
  x/incentive/keeper/reward_tracker.go
  x/incentive/keeper/reward_tracker_test.go
  x/incentive/types/genesis.pb.go
  x/incentive/types/genesis_test.go
  x/incentive/types/incentive.go
  x/incentive/types/incentive_test.go
  x/incentive/types/tx.pb.go
Labels: api breaking, backport-to-release/v1.x

#622 backport: chore(incentive): rename `btc_delegation` stakeholder type to `btc_staker` (#589)
  CHANGELOG.md
  docs/register-bitcoin-stake.md
  proto/babylon/incentive/genesis.proto
  proto/babylon/incentive/tx.proto
  test/e2e/btc_rewards_distribution_e2e_test.go
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  x/finality/keeper/msg_server_test.go
  x/incentive/client/cli/tx.go
  x/incentive/keeper/btc_staking_gauge_test.go
  x/incentive/keeper/msg_server_test.go
  x/incentive/keeper/reward_gauge.go
  x/incentive/keeper/reward_gauge_test.go
  x/incentive/keeper/reward_tracker.go
  x/incentive/keeper/reward_tracker_test.go
  x/incentive/types/genesis.pb.go
  x/incentive/types/genesis_test.go
  x/incentive/types/incentive.go
  x/incentive/types/incentive_test.go
  x/incentive/types/tx.pb.go
Labels: api breaking

#631 ignore expire events when there is no covenant quorum
  CHANGELOG.md
  testutil/btcstaking-helper/keeper.go
  x/finality/keeper/power_dist_change.go
  x/finality/keeper/power_dist_change_test.go
  x/finality/types/expected_keepers.go
  x/finality/types/mocked_keepers.go
Labels: consensus breaking, backport-to-release/v1.x

#648 feat: add query to iterate over all parameters in btcstaking
  CHANGELOG.md
  client/docs/swagger-ui/swagger.yaml
  proto/babylon/btcstaking/v1/query.proto
  x/btcstaking/client/cli/query.go
  x/btcstaking/client/cli/query_params.go
  x/btcstaking/keeper/grpc_query.go
  x/btcstaking/keeper/grpc_query_test.go
  x/btcstaking/types/query.pb.go
  x/btcstaking/types/query.pb.gw.go
Labels: backport-to-release/v1.x

#658 crypto: check if Z==1 in ToBTCPK
  CHANGELOG.md
  crypto/schnorr-adaptor-signature/keys.go
  crypto/schnorr-adaptor-signature/keys_test.go
  crypto/schnorr-adaptor-signature/sig.go
Labels: backport-to-release/v1.x

#656 crypto: fix adaptor sig validity and typos
  CHANGELOG.md
  crypto/schnorr-adaptor-signature/keys.go
  crypto/schnorr-adaptor-signature/keys_test.go
  crypto/schnorr-adaptor-signature/sign_utils.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/types/btc_slashing_tx.go
  x/btcstaking/types/btc_slashing_tx_test.go
  x/btcstaking/types/btc_undelegation_test.go
Labels: backport-to-release/v1.x

#660 add function to recover pub key from sig
  CHANGELOG.md
  crypto/ecdsa/ecdsa.go
  crypto/ecdsa/ecdsa_test.go
  x/btcstaking/types/pop.go
  x/btcstaking/types/pop_test.go
Labels: backport-to-release/v1.x

#673 move bip322 signing functions to testutil package
  CHANGELOG.md
  crypto/bip322/bip322.go
  crypto/bip322/bip322_test.go
  testutil/datagen/pop.go
Labels: backport-to-release/v1.x

#668 crypto: remove unused unsafe key gen function
  CHANGELOG.md
  crypto/bls12381/bls.go
  testutil/datagen/secp256k1.go
Labels: backport-to-release/v1.x

#667 crypto: Enable group check in BLS
  CHANGELOG.md
  crypto/bls12381/bls.go
  crypto/bls12381/types_bench_test.go
Labels: backport-to-release/v1.x

#675 Add send msg / send msgs helpers to babylon client
  CHANGELOG.md
  client/client/tx.go
Labels: backport-to-release/v1.x

#676 chore(deps): bump IBC-go to v8.7.0
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport-to-release/v1.x

#644 chore(mempool): add priority nonce mempool and tx priority logic
  CHANGELOG.md
  app/ante/ante.go
  app/ante/priority.go
  app/ante/priority_test.go
  app/app.go
  cmd/babylond/cmd/custom_babylon_config.go
  x/checkpointing/prepare/proposal.go
  x/checkpointing/prepare/proposal_test.go
Labels: backport-to-release/v1.x

#683 crypto: fix eots signing timing attack
  CHANGELOG.md
  crypto/eots/eots.go
Labels: backport-to-release/v1.x

#685 fix doc
  docs/register-bitcoin-stake.md
Labels: A:no-changelog, backport-to-release/v1.x

#680 crypto: fix bls rogue attack
  CHANGELOG.md
  app/signer/types.go
  crypto/bls12381/bls.go
  crypto/bls12381/bls_test.go
  crypto/bls12381/types.go
  crypto/bls12381/types_bench_test.go
  x/checkpointing/types/pop.go
Labels: backport-to-release/v1.x

#693 chore: use timeout from config in bbn client
  CHANGELOG.md
  client/babylonclient/tx.go
Labels: backport-to-release/v1.x

#699 chore: Upgrade blst
  go.mod
  go.sum
Labels: A:no-changelog, backport-to-release/v1.x

#691 crypto: fix EOTS missing normalization in use of secp256k1.FieldVal
  CHANGELOG.md
  crypto/eots/eots.go
  types/btc_schnorr_pub_rand.go
  types/btc_schnorr_pub_rand_test.go
  x/finality/types/finality.go
  x/finality/types/msg.go
Labels: backport-to-release/v1.x

#694 crypto: fix missing secret zeroized
  crypto/bls12381/bls.go
  crypto/eots/eots.go
Labels: A:no-changelog, backport-to-release/v1.x

#682 feat: Avoid creating pop in babylond tx checkpointing create-validator
  CHANGELOG.md
  app/signer/bls.go
  app/signer/types.go
  cmd/babylond/cmd/generate_bls_pop.go
  cmd/babylond/cmd/generate_bls_pop_test.go
  cmd/babylond/cmd/root.go
  x/checkpointing/client/cli/tx.go
  x/checkpointing/client/cli/tx_test.go
  x/checkpointing/client/cli/utils.go
Labels: backport-to-release/v1.x

#671 crypto: align adaptor sig impl with Blockstream spec
  CHANGELOG.md
  crypto/schnorr-adaptor-signature/README.md
  crypto/schnorr-adaptor-signature/keys.go
  crypto/schnorr-adaptor-signature/keys_test.go
  crypto/schnorr-adaptor-signature/sig.go
  crypto/schnorr-adaptor-signature/sig_test.go
  crypto/schnorr-adaptor-signature/sign_utils.go
  crypto/schnorr-adaptor-signature/types.go
  crypto/schnorr-adaptor-signature/types_test.go
  crypto/schnorr-adaptor-signature/vectors/README.md
  crypto/schnorr-adaptor-signature/vectors/adapt_vectors.csv
  crypto/schnorr-adaptor-signature/vectors/presig_vectors.csv
  crypto/schnorr-adaptor-signature/vectors/secadaptor_vectors.csv
  crypto/schnorr-adaptor-signature/vectors_test.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/types/btc_slashing_tx.go
  x/btcstaking/types/btc_slashing_tx_test.go
  x/btcstaking/types/btc_undelegation_test.go
  x/checkpointing/keeper/registration_state.go
  x/checkpointing/types/keys.go
Labels: backport-to-release/v1.x

#701 chore(upgrade): update upgrade to v1rc8
  CHANGELOG.md
  app/include_upgrade_testnet.go
  app/upgrades/v1rc8/testnet/upgrade.go
  app/upgrades/v1rc8/testnet/upgrade_test.go
Labels: backport-to-release/v1.x

#695 improve checkpoint panic behaviour
  CHANGELOG.md
  x/btccheckpoint/keeper/msg_server.go
  x/btccheckpoint/keeper/msg_server_test.go
  x/btccheckpoint/keeper/submissions.go
  x/btccheckpoint/types/mock_keepers.go
Labels: security, consensus breaking, backport-to-release/v1.x

#689 improved randomness generation
  crypto/common/common.go
Labels: A:no-changelog, backport-to-release/v1.x

#712 fix: emit double events in queued msgs at end epoch
  CHANGELOG.md
  x/epoching/abci.go
  x/epoching/keeper/msg_server_test.go
Labels: backport-to-release/v1.x

#690 feat: support password for bls key through env variable
  CHANGELOG.md
  app/signer/bls.go
  app/signer/bls_test.go
  app/signer/private.go
  app/signer/util.go
  cmd/babylond/cmd/cmd_test.go
  cmd/babylond/cmd/create_bls_key.go
  cmd/babylond/cmd/flags.go
  cmd/babylond/cmd/init.go
  cmd/babylond/cmd/migrate_bls_key.go
  cmd/babylond/cmd/migrate_bls_key_test.go
  cmd/babylond/cmd/root.go
  docs/bls_key_password_management.md
  testutil/datagen/init_val.go
Labels: api breaking, backport-to-release/v1.x

#726 update release process to take account of major version
  RELEASE_PROCESS.md
Labels: A:no-changelog, backport-to-release/v1.x

#731 chore: fix block timeout in Babylon client
  CHANGELOG.md
  client/config/babylon_config.go
Labels: backport-to-release/v1.x

#749 chore: add dumb v1rc9 upgrade
  CHANGELOG.md
  app/include_upgrade_testnet.go
  app/upgrades/v1rc9/testnet/upgrade.go
Labels: backport-to-release/v1.x

#745 limit number of finalized and rewarded blocks
  CHANGELOG.md
  x/finality/abci.go
  x/finality/keeper/gov.go
  x/finality/keeper/gov_test.go
  x/finality/keeper/rewarding.go
  x/finality/keeper/rewarding_test.go
  x/finality/keeper/tallying.go
  x/finality/keeper/tallying_bench_test.go
  x/finality/keeper/tallying_test.go
  x/finality/types/constants.go
Labels: consensus breaking, backport-to-release/v1.x

#748 fix: resume finality
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  test/e2e/btc_rewards_distribution_e2e_test.go
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  test/e2e/configurer/chain/fp.go
  test/e2e/configurer/chain/queries_btcstaking.go
  test/e2e/configurer/chain/upgrade.go
  test/e2e/configurer/config/constants.go
  test/e2e/configurer/upgrade.go
  test/e2e/e2e_test.go
  test/e2e/govProps/resume-finality.json
  test/e2e/gov_finality_resume.go
  test/e2e/software_upgrade_e2e_v1_test.go
  x/finality/abci.go
  x/finality/keeper/gov.go
  x/finality/keeper/gov_test.go
  x/finality/keeper/tallying.go
Labels: consensus breaking, backport-to-release/v1.x

#746 chore: upgrade parameters
  CHANGELOG.md
  app/include_upgrade_mainnet.go
  app/include_upgrade_testnet.go
  app/upgrades/v1/data_params_test.go
  app/upgrades/v1/data_token_distribution_test.go
  app/upgrades/v1/mainnet/btcstaking_params.go
  app/upgrades/v1/mainnet/finality_params.go
  app/upgrades/v1/mainnet/incentive.go
  app/upgrades/v1/mainnet/params_update.go
  app/upgrades/v1/mainnet/token_distribution.go
  app/upgrades/v1/testnet/params_update.go
  app/upgrades/v1/upgrades.go
  app/upgrades/v1/upgrades_test.go
Labels: backport-to-release/v1.x

#741 chore: fix register consumer CLI
  CHANGELOG.md
  x/btcstkconsumer/client/cli/tx.go
Labels: backport-to-relaese/v1.99.0-devnet.6.x

#757 chore: go releaser testnet + wasm statically
  .github/workflows/goreleaser.yml
  .goreleaser.yml
  CHANGELOG.md
  Makefile
Labels: backport-to-release/v1.x

#764 chore: Update btc activation, finality activation, and allow list expiry height
  app/upgrades/v1/mainnet/btcstaking_params.go
  app/upgrades/v1/mainnet/finality_params.go
  x/finality/types/params.go
Labels: A:no-changelog, backport-to-release/v1.x
