Repository babylonlabs-io/babylon, pull requests merged in 2025-06, with the labels that each got.

#1009 chore: cl release v2rc1 (#1008)
  CHANGELOG.md
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#1004 fix: use correct err type in MsgResumeFinalityProposal validate basic
  x/finality/types/msg.go
  x/finality/types/msg_test.go
Labels: A:no-changelog

#1013 chore: ibcratelimit `v8.1.0` begin blocker fix
  CHANGELOG.md
  app/app.go
  go.mod
  go.sum
  x/rate-limiting/module.go
Labels: backport-to-release/v2.x

#702 chore: add test to verify against small amount sent to fee collector
  CHANGELOG.md
  x/incentive/keeper/intercept_fee_collector_test.go
Labels: security

#1018 chore: update genesis validations in x/mint and x/btccheckpoint
  CHANGELOG.md
  x/btccheckpoint/keeper/genesis_test.go
  x/btccheckpoint/types/genesis.go
  x/btccheckpoint/types/genesis_test.go
  x/finality/keeper/power_dist_change.go
  x/mint/module.go
Labels: backport-to-release/v2.x

#1030 chore: rename upgrade from v2rc1 to v2rc2
  CHANGELOG.md
  app/include_upgrade_testnet.go
  app/upgrades/v2/upgrades.go
  app/upgrades/v2rc2/testnet/upgrade.go
Labels: backport-to-release/v2.x

#1034 chore(btcstaking): remove redundant ValidateBasic call
  CHANGELOG.md
  x/btcstaking/keeper/msg_server.go
Labels: backport-to-release/v2.x

#1046 chore(btcstaking): update genesis & validations
  CHANGELOG.md
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/genesis.go
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/btcstaking.go
  x/btcstaking/types/create_delegation_parser.go
  x/btcstaking/types/genesis.go
  x/btcstaking/types/msg.go
  x/btcstaking/types/params.go
Labels: backport-to-release/v2.x

#1040 chore(btcstkconsumer): rename ETH L2 to rollup
  CHANGELOG.md
  client/docs/swagger-ui/swagger.yaml
  go.sum
  proto/babylon/btcstkconsumer/v1/btcstkconsumer.proto
  proto/babylon/btcstkconsumer/v1/events.proto
  proto/babylon/btcstkconsumer/v1/query.proto
  proto/babylon/btcstkconsumer/v1/tx.proto
  test/e2e/configurer/chain/commands_btcstkconsumer.go
  test/e2e/e2e_test.go
  test/replay/driver.go
  testutil/datagen/btcstkconsumer.go
  x/btcstkconsumer/client/cli/tx.go
  x/btcstkconsumer/keeper/msg_server.go
  x/btcstkconsumer/keeper/msg_server_test.go
  x/btcstkconsumer/types/btcstkconsumer.pb.go
  x/btcstkconsumer/types/consumer_register.go
  x/btcstkconsumer/types/errors.go
  x/btcstkconsumer/types/events.go
  x/btcstkconsumer/types/events.pb.go
  x/btcstkconsumer/types/query.pb.go
  x/btcstkconsumer/types/tx.pb.go
Labels: backport-to-release/v4.x, conflicts

#1061 chore: add validation of msg hashes size and decode
  CHANGELOG.md
  x/incentive/types/genesis.go
  x/incentive/types/genesis_test.go
Labels: backport-to-release/v2.x

#1070 fix: validation for vp dist cache
  CHANGELOG.md
  x/finality/types/power_table.go
  x/finality/types/power_table_test.go
Labels: backport-to-release/v2.x

#1064 fix: signing info validation for start height and missed block counter
  CHANGELOG.md
  x/finality/types/signing_info.go
  x/finality/types/signing_info_test.go
Labels: backport-to-release/v2.x

#1078 fix: enforce check tx even without check tx
  CHANGELOG.md
  app/ante/ibc_msg_size.go
  app/ante/ibc_msg_size_test.go
Labels: backport-to-release/v2.x

#1082 chore: val sequential epoch
  CHANGELOG.md
  x/epoching/types/genesis.go
  x/epoching/types/genesis_test.go
Labels: backport-to-release/v2.x

#1085 imp(incentive): fix comment
  CHANGELOG.md
  x/incentive/keeper/reward_tracker_events.go
Labels: backport-to-release/v2.x

#1084 imp(incentive): check TotalActiveSat amt in subFinalityProviderStaked
  CHANGELOG.md
  x/incentive/keeper/reward_tracker_store.go
  x/incentive/keeper/reward_tracker_store_test.go
  x/incentive/types/errors.go
Labels: backport-to-release/v2.x

#1097 imp(finality): update Evidence ValidateBasic
  CHANGELOG.md
  x/finality/types/finality.go
  x/finality/types/finality_test.go
Labels: backport-to-release/v2.x

#1071 chore: update `fpdistributioninfo` validations
  CHANGELOG.md
  x/finality/types/genesis_test.go
  x/finality/types/power_table.go
  x/finality/types/power_table_test.go
Labels: backport-to-release/v2.x

#1096 chore: validate stats positive
  CHANGELOG.md
  x/incentive/types/rewards.go
  x/incentive/types/rewards_test.go
Labels: backport-to-release/v2.x

#1119 fix: TestGenesis in btcstaking
  testutil/keeper/btccheckpoint.go
  x/btccheckpoint/keeper/genesis_test.go
  x/btcstaking/genesis_test.go
Labels: A:no-changelog

#1118 chore(checkpointing): update validations
  CHANGELOG.md
  testutil/datagen/raw_checkpoint.go
  x/checkpointing/types/checkpoint.go
  x/checkpointing/types/checkpoint_test.go
  x/checkpointing/types/errors.go
  x/checkpointing/types/genesis_test.go
  x/checkpointing/types/types.go
  x/checkpointing/types/types_test.go
Labels: backport-to-release/v2.x

#1128 fix: validate genesis fp historic reward entries
  CHANGELOG.md
  x/incentive/keeper/genesis_test.go
  x/incentive/types/genesis.go
  x/incentive/types/genesis_test.go
Labels: backport-to-release/v2.x

#1065 fix: add check for rewards period
  CHANGELOG.md
  x/incentive/types/rewards.go
  x/incentive/types/rewards_test.go
Labels: backport-to-release/v2.x

#1135 imp(incentive): validate `LastProcessedHeightEventRewardTracker` on `InitGenesis`
  CHANGELOG.md
  x/incentive/keeper/genesis.go
  x/incentive/keeper/genesis_test.go
Labels: backport-to-release/v2.x

#1102 imp(incentive): handle empty btc staking gauge when no fees collected
  CHANGELOG.md
  x/incentive/keeper/btc_staking_gauge.go
  x/incentive/keeper/btc_staking_gauge_test.go
  x/mint/keeper/genesis.go
  x/mint/module.go
  x/mint/types/genesis.go
Labels: backport-to-release/v2.x

#1152 chore: validate power non negative
  CHANGELOG.md
  x/epoching/types/epoching.go
  x/epoching/types/epoching_test.go
Labels: backport-to-release/v2.x

#1146 chore: remove `x/crisis`
  CHANGELOG.md
  app/app.go
  app/export.go
  app/keepers/keepers.go
  app/upgrades/v2/upgrades.go
  app/upgrades/v2/upgrades_test.go
  app/upgrades/v2rc2/testnet/upgrade.go
  cmd/babylond/cmd/genesis.go
  cmd/babylond/cmd/root.go
  test/e2e/initialization/config.go
Labels: backport-to-release/v2.x

#1136 fix(btccheckpoint): update submission dup validation
  CHANGELOG.md
  x/btccheckpoint/types/genesis.go
Labels: backport-to-release/v2.x

#1151 chore: add whitelisted channels to add rate limit
  CHANGELOG.md
  app/include_upgrade_mainnet.go
  app/include_upgrade_testnet.go
  app/upgrades/v2/upgrades.go
  app/upgrades/v2/upgrades_test.go
Labels: backport-to-release/v2.x

#1168 chore: removed duplicated check for addr len
  CHANGELOG.md
  app/params/config.go
Labels: backport-to-release/v2.x

#1174 chore: reduced ibc `MaxAddressSize` to max value of bech 32 addr (90)
  CHANGELOG.md
  app/ante/ibc_msg_size.go
Labels: backport-to-release/v2.x

#1171 chore: add validation for DelegationStateUpdate
  CHANGELOG.md
  testutil/datagen/epoching.go
  x/epoching/types/epoching.go
  x/epoching/types/epoching_test.go
Labels: backport-to-release/v2.x

#1186 chore: add v2.0.0-rc.3 to cl
  CHANGELOG.md
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#1196 fix: checks for pagination in `QueryBlsPublicKeyListRequest`
  CHANGELOG.md
  x/checkpointing/keeper/grpc_query_bls.go
  x/checkpointing/keeper/grpc_query_bls_test.go
  x/checkpointing/types/bls_key.go
Labels: backport-to-release/v2.x

#1197 fix: bad ubd fee in btcstaking Params
  CHANGELOG.md
  btcstaking/errors.go
  test/replay/btcstaking_test.go
  x/btcstaking/types/params.go
  x/btcstaking/types/params_test.go
  x/btcstaking/types/validate_parsed_message_test.go
Labels: backport-to-release/v2.x

#1216 chore: add v2.0.0-rc.4 to cl
  CHANGELOG.md
Labels: backport-to-release/v3.x

#1060 imp(finality): optimize PubRandCommit lookup
  CHANGELOG.md
  proto/babylon/finality/v1/finality.proto
  proto/babylon/finality/v1/genesis.proto
  testutil/datagen/finality.go
  testutil/keeper/finality.go
  x/finality/keeper/genesis.go
  x/finality/keeper/genesis_test.go
  x/finality/keeper/keeper.go
  x/finality/keeper/migrations.go
  x/finality/keeper/msg_server.go
  x/finality/keeper/msg_server_test.go
  x/finality/keeper/power_dist_change_test.go
  x/finality/keeper/public_randomness.go
  x/finality/keeper/public_randomness_test.go
  x/finality/migrations/v2/store.go
  x/finality/migrations/v2/store_test.go
  x/finality/module.go
  x/finality/types/constants.go
  x/finality/types/finality.pb.go
  x/finality/types/genesis.go
  x/finality/types/genesis.pb.go
  x/finality/types/keys.go
Labels: backport-to-release/v3.x

#1028 chore: Bump IBC to V2
  CHANGELOG.md
  app/ante/ante.go
  app/ante/ibc_msg_size.go
  app/ante/ibc_msg_size_test.go
  app/app.go
  app/app_test.go
  app/keepers/keepers.go
  app/modules.go
  app/upgrades/v2/upgrades.go
  app/upgrades/v2/upgrades_test.go
  client/query/ibc.go
  cmd/babylond/cmd/genesis.go
  go.mod
  go.sum
  test/e2e/configurer/chain/chain.go
  test/e2e/configurer/chain/commands.go
  test/e2e/configurer/chain/queries.go
  test/e2e/configurer/chain/queries_ibc.go
  test/e2e/ibc_transfer_e2e_test.go
  test/e2e/ica_e2e_test.go
  test/e2e/initialization/config.go
  test/replay/btcstaking_test.go
  testutil/datagen/tendermint.go
  testutil/keeper/zoneconcierge.go
  x/btcstkconsumer/keeper/msg_server_test.go
  x/btcstkconsumer/types/expected_keepers.go
  x/zoneconcierge/genesis_test.go
  x/zoneconcierge/keeper/epoch_chain_info_indexer_test.go
  x/zoneconcierge/keeper/genesis.go
  x/zoneconcierge/keeper/genesis_test.go
  x/zoneconcierge/keeper/grpc_query_test.go
  x/zoneconcierge/keeper/ibc_channels.go
  x/zoneconcierge/keeper/ibc_header_decorator.go
  x/zoneconcierge/keeper/ibc_packet.go
  x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
  x/zoneconcierge/keeper/keeper.go
  x/zoneconcierge/keeper/keeper_test.go
  x/zoneconcierge/keeper/params_test.go
  x/zoneconcierge/keeper/proof_btc_timestamp_test.go
  x/zoneconcierge/module.go
  x/zoneconcierge/module_ibc.go
  x/zoneconcierge/types/expected_keepers.go
  x/zoneconcierge/types/genesis.go
  x/zoneconcierge/types/keys.go
  x/zoneconcierge/types/mocked_keepers.go
Labels: backport-to-release/v3.x

#1235 delete outdated doc
  docs/transaction-impl-spec.md
Labels: A:no-changelog, backport-to-release/v3.x

#1249 Backport v2.1 fix to staking endblocker
  CHANGELOG.md
  app/app.go
  app/app_test.go
Labels: backport-to-release/v3.x

#1246 revert: feat(btcstaking,btcstkconsumer): Add max_multi_staked_fps validation and single FP per consumer constraint #944
  CHANGELOG.md
  client/docs/swagger-ui/swagger.yaml
  proto/babylon/btcstkconsumer/v1/btcstkconsumer.proto
  proto/babylon/btcstkconsumer/v1/events.proto
  proto/babylon/btcstkconsumer/v1/query.proto
  proto/babylon/btcstkconsumer/v1/tx.proto
  test/e2e/configurer/chain/commands_btcstkconsumer.go
  test/e2e/finality_contract_e2e_test.go
  test/replay/btcstaking_test.go
  test/replay/driver.go
  testutil/datagen/btcstkconsumer.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/restaking_test.go
  x/btcstaking/types/errors.go
  x/btcstaking/types/expected_keepers.go
  x/btcstaking/types/mocked_keepers.go
  x/btcstkconsumer/client/cli/tx.go
  x/btcstkconsumer/keeper/consumer_registry.go
  x/btcstkconsumer/keeper/consumer_registry_test.go
  x/btcstkconsumer/keeper/finality_provider_registry_test.go
  x/btcstkconsumer/keeper/grpc_query_test.go
  x/btcstkconsumer/keeper/msg_server.go
  x/btcstkconsumer/keeper/msg_server_test.go
  x/btcstkconsumer/types/btcstkconsumer.pb.go
  x/btcstkconsumer/types/consumer_register.go
  x/btcstkconsumer/types/consumer_register_test.go
  x/btcstkconsumer/types/errors.go
  x/btcstkconsumer/types/events.go
  x/btcstkconsumer/types/events.pb.go
  x/btcstkconsumer/types/genesis_test.go
  x/btcstkconsumer/types/query.pb.go
  x/btcstkconsumer/types/tx.pb.go
  x/zoneconcierge/types/mocked_keepers.go
Labels: backport-to-release/v3.x

#1256 chore: remove query chains info request from zoneconcierge module
  CHANGELOG.md
  client/query/zoneconcierge.go
  proto/babylon/zoneconcierge/v1/query.proto
  x/zoneconcierge/client/cli/query.go
  x/zoneconcierge/keeper/grpc_query.go
  x/zoneconcierge/keeper/grpc_query_test.go
  x/zoneconcierge/types/query.pb.go
  x/zoneconcierge/types/query.pb.gw.go
Labels: backport-to-release/v3.x

#1260 update mergify rules
  .mergify.yml
Labels: A:no-changelog
