Repository babylonlabs-io/babylon, pull requests merged in 2025-04, with the labels that each got.

#761 chore: add allowed tx hash to upgrade data
  CHANGELOG.md
  app/upgrades/v1/mainnet/allowed_staking_tx_hashes.go
Labels: backport-to-release/v1.x

#780 crypto: remove Verify for ECDSA
  CHANGELOG.md
  crypto/ecdsa/ecdsa.go
  crypto/ecdsa/ecdsa_test.go
Labels: backport-to-release/v1.x

#781 docs: Add warning about using correct params
  docs/register-bitcoin-stake.md
Labels: A:no-changelog, backport-to-release/v1.x

#778 Fix: typo edits registration-eligibility.md
  x/btcstaking/docs/registration-eligibility.md
Labels: A:no-changelog, backport-to-release/v1.x

#789 (fix) ibc-relayer.md hermes example
  docs/ibc-relayer.md
Labels: A:no-changelog, backport-to-release/v1.x

#793 fix: BLS key will be overwritten when the password is not retrieved
  CHANGELOG.md
  app/signer/bls.go
  app/signer/bls_test.go
  app/signer/private.go
  app/signer/util.go
  cmd/babylond/cmd/cmd_test.go
  cmd/babylond/cmd/create_bls_key.go
  cmd/babylond/cmd/flags.go
  cmd/babylond/cmd/init.go
  cmd/babylond/cmd/root.go
  cmd/babylond/cmd/show_bls_key.go
  crypto/eots/eots_test.go
  test/e2e/containers/containers.go
  testutil/datagen/init_val.go
Labels: backport-to-release/v1.x

#796 fix: goreleaser for mainnet
  .goreleaser.yml
  CHANGELOG.md
Labels: backport-to-release/v1.x

#802 clean up resources from TmpAppOptions
  CHANGELOG.md
  app/app_test.go
  app/encoding.go
  cmd/babylond/cmd/genhelpers/gentx_test.go
  cmd/babylond/cmd/testnet_test.go
  testutil/keeper/btclightclient.go
Labels: backport-to-release/v1.x

#826 Framework for determinisitc tests for btcstaking protocol
  test/replay/app_replay_e2e_test.go
  test/replay/btcstaking_test.go
  test/replay/covenant_sender.go
  test/replay/driver.go
  test/replay/driver_queries.go
  test/replay/finality_provider_sender.go
  test/replay/finality_test.go
  test/replay/replayer.go
  test/replay/scenario_builder.go
  test/replay/staker_sender.go
  testutil/datagen/btcstaking.go
  x/finality/keeper/power_dist_change_test.go
Labels: A:no-changelog

#842 fix: btc stk hook of btclightclient
  CHANGELOG.md
  app/keepers/keepers.go
  cmd/babylond/cmd/cmd_test.go
Labels: backport-to-release/v2.x

#829 fix: add checks for slashed fp in gov resume finality
  CHANGELOG.md
  cmd/babylond/cmd/cmd_test.go
  test/e2e/initialization/config.go
  test/replay/btcstaking_test.go
  test/replay/driver.go
  test/replay/driver_queries.go
  test/replay/finality_provider_sender.go
  test/replay/finality_test.go
  test/replay/gov.go
  test/replay/scenario_builder.go
  x/btccheckpoint/keeper/genesis_test.go
  x/finality/keeper/gov.go
  x/finality/keeper/gov_test.go
Labels: backport-to-release/v2.x, backport-to-release/v1.1.x

#846 feat: Add tokenfactory module
  CHANGELOG.md
  app/app.go
  app/app_test.go
  app/keepers/keepers.go
  app/upgrades/v2/upgrades.go
  go.mod
  go.sum
  wasmbinding/wasm.go
Labels: consensus breaking, backport-to-release/v2.x
