Repository babylonlabs-io/babylon, pull requests merged in 2025-07, with the labels that each got.

#1265 chore(zoneconcierge): Remove `ListEpochHeaders` and `QueryChainList` query
  CHANGELOG.md
  client/docs/swagger-ui/swagger.yaml
  client/query/zoneconcierge.go
  go.mod
  proto/babylon/zoneconcierge/v1/query.proto
  x/zoneconcierge/keeper/grpc_query.go
  x/zoneconcierge/keeper/grpc_query_test.go
  x/zoneconcierge/types/query.pb.go
  x/zoneconcierge/types/query.pb.gw.go
Labels: backport-to-release/v3.x

#1269 chore(tests): add fee collector tests
  CHANGELOG.md
  test/e2e/configurer/chain/commands.go
  test/e2e/containers/config.go
  test/e2e/ibc_transfer_e2e_test.go
Labels: backport-to-release/v2.2.x

#1062 chore(incentive): Add `anteHandler` to avoid fee grants on refundable tx
  CHANGELOG.md
  app/ante/ante.go
  testutil/keeper/incentive.go
  x/incentive/README.md
  x/incentive/keeper/keeper_test.go
  x/incentive/keeper/msg_server.go
  x/incentive/keeper/refund_tx_decorator.go
  x/incentive/keeper/refund_tx_decorator_test.go
  x/incentive/keeper/refundable_msg_index.go
  x/incentive/types/expected_keepers.go
Labels: backport-to-release/v3.x

#1292 chore: Use correct multi-staking terminology
  CHANGELOG.md
  btcstaking/btcstaking_test.go
  client/docs/swagger-ui/swagger.yaml
  proto/babylon/btcstaking/v1/btcstaking.proto
  proto/babylon/btcstaking/v1/events.proto
  proto/babylon/btcstaking/v1/packet.proto
  x/btcstaking/README.md
  x/btcstaking/keeper/btc_consumer_delegations.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/btc_staking_consumer_events_test.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/restaking_test.go
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/btc_delegation_test.go
  x/btcstaking/types/btc_slashing_tx.go
  x/btcstaking/types/btc_slashing_tx_test.go
  x/btcstaking/types/btc_undelegation.go
  x/btcstaking/types/btc_undelegation_test.go
  x/btcstaking/types/btcstaking.pb.go
  x/btcstaking/types/errors.go
  x/btcstaking/types/events.pb.go
  x/btcstaking/types/packet.pb.go
  x/finality/keeper/power_dist_change.go
Labels: A:no-changelog

#1231 imp(btc-staking): stake expansion
  CHANGELOG.md
  btcstaking/staking.go
  client/docs/swagger-ui/swagger.yaml
  proto/babylon/btcstaking/v1/btcstaking.proto
  proto/babylon/btcstaking/v1/events.proto
  proto/babylon/btcstaking/v1/query.proto
  proto/babylon/btcstaking/v1/tx.proto
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  test/e2e/finality_contract_e2e_test.go
  test/e2e/gov_finality_resume.go
  test/replay/btcstaking_test.go
  test/replay/covenant_sender.go
  test/replay/driver.go
  test/replay/driver_queries.go
  test/replay/staker_sender.go
  testutil/btcstaking-helper/keeper.go
  testutil/datagen/btcstaking.go
  testutil/incentives-helper/keeper.go
  types/btc_schnorr_pk.go
  x/btcstaking/client/cli/tx.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/btc_staking_consumer_events_test.go
  x/btcstaking/keeper/grpc_query.go
  x/btcstaking/keeper/inclusion_proof.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/keeper/multistaking_test.go
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/btc_delegation_test.go
  x/btcstaking/types/btcstaking.pb.go
  x/btcstaking/types/codec.go
  x/btcstaking/types/create_delegation_parser.go
  x/btcstaking/types/errors.go
  x/btcstaking/types/events.go
  x/btcstaking/types/events.pb.go
  x/btcstaking/types/msg.go
  x/btcstaking/types/msg_test.go
  x/btcstaking/types/query.go
  x/btcstaking/types/query.pb.go
  x/btcstaking/types/tx.pb.go
  x/btcstaking/types/validate_parsed_message_test.go
  x/finality/keeper/power_dist_change.go
  x/finality/types/expected_keepers.go
  x/finality/types/mocked_keepers.go
Labels: backport-to-release/v3.x

#1318 fix secret key propagation when slashing
  CHANGELOG.md
  x/btcstaking/keeper/finality_providers.go
  x/btcstaking/keeper/keeper_test.go
  x/btcstaking/types/btc_staking_consumer_events.go
  x/finality/keeper/evidence.go
  x/finality/keeper/msg_server.go
  x/finality/keeper/msg_server_test.go
  x/finality/types/expected_keepers.go
  x/finality/types/mocked_keepers.go
  x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go
  x/zoneconcierge/types/expected_keepers.go
Labels: consensus breaking, backport-to-release/v3.x

#1321 fix: issue with compilation of mocked keeper
  x/btcstaking/types/mocked_keepers.go
  x/finality/types/mocked_keepers.go
  x/zoneconcierge/types/mocked_keepers.go
Labels: A:no-changelog, backport-to-release/v3.x

#1324 fix(zoneconcierge): remove fork related logic from zoneconcierge
  CHANGELOG.md
  proto/babylon/zoneconcierge/v1/genesis.proto
  proto/babylon/zoneconcierge/v1/query.proto
  proto/babylon/zoneconcierge/v1/zoneconcierge.proto
  testutil/datagen/zoneconcierge.go
  x/zoneconcierge/keeper/chain_info_indexer.go
  x/zoneconcierge/keeper/epoch_chain_info_indexer_test.go
  x/zoneconcierge/keeper/fork_indexer.go
  x/zoneconcierge/keeper/fork_indexer_test.go
  x/zoneconcierge/keeper/genesis.go
  x/zoneconcierge/keeper/genesis_test.go
  x/zoneconcierge/keeper/grpc_query.go
  x/zoneconcierge/keeper/grpc_query_test.go
  x/zoneconcierge/keeper/header_handler.go
  x/zoneconcierge/keeper/keeper_test.go
  x/zoneconcierge/types/genesis.go
  x/zoneconcierge/types/genesis.pb.go
  x/zoneconcierge/types/keys.go
  x/zoneconcierge/types/query.pb.go
  x/zoneconcierge/types/zoneconcierge.go
  x/zoneconcierge/types/zoneconcierge.pb.go
  x/zoneconcierge/types/zoneconcierge_test.go
Labels: backport-to-release/v3.x

#1288 chore(zoneconcierge): remove unused queries from `x/zoneconcierge`
  CHANGELOG.md
  client/docs/swagger-ui/swagger.yaml
  client/query/zoneconcierge.go
  proto/babylon/zoneconcierge/v1/query.proto
  x/zoneconcierge/client/cli/query.go
  x/zoneconcierge/keeper/grpc_query.go
  x/zoneconcierge/keeper/grpc_query_test.go
  x/zoneconcierge/types/query.pb.go
  x/zoneconcierge/types/query.pb.gw.go
Labels: backport-to-release/v3.x

#1343 add max params to external commands
  CHANGELOG.md
  cmd/babylond/cmd/flags.go
  cmd/babylond/cmd/genesis.go
  cmd/babylond/cmd/testnet.go
  x/btcstaking/types/genesis_test.go
  x/btcstaking/types/params.go
Labels: backport-to-release/v3.x

#1344 fix: bump cosmos-sdk and remove send restrictions
  CHANGELOG.md
  app/ante/fee_checker.go
  app/ante/fee_checker_test.go
  app/keepers/keepers.go
  go.mod
  go.sum
  test/e2e/ibc_transfer_e2e_test.go
Labels: backport-to-release/v2.3.x

#1352 imp: add stake expansion sigs in btc del query response
  CHANGELOG.md
  proto/babylon/btcstaking/v1/query.proto
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/query.pb.go
Labels: backport-to-release/v3.x

#1366 fix: do not add multistaked fps to voting table
  CHANGELOG.md
  test/replay/btcstaking_test.go
  test/replay/finality_test.go
  test/replay/multistaking_test.go
  x/btcstaking/keeper/finality_providers.go
  x/finality/keeper/grpc_query.go
  x/finality/keeper/grpc_query_test.go
  x/finality/keeper/msg_server.go
  x/finality/keeper/msg_server_test.go
  x/finality/keeper/power_dist_change.go
  x/finality/keeper/power_table.go
  x/finality/types/expected_keepers.go
  x/finality/types/mocked_keepers.go
Labels: backport-to-release/v3.x

#1369 fix: update stk exp validations
  CHANGELOG.md
  x/btcstaking/keeper/msg_server.go
Labels: backport-to-release/v3.x

#1360 fix(zoneconcierge): don't panic on IBC send packet calls
  CHANGELOG.md
  x/zoneconcierge/abci.go
  x/zoneconcierge/keeper/hooks.go
  x/zoneconcierge/keeper/ibc_packet.go
  x/zoneconcierge/keeper/ibc_packet_btc_headers.go
  x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
Labels: backport-to-release/v3.x

#1375 strict requirements for multi staking
  CHANGELOG.md
  docs/register-bitcoin-stake.md
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/keeper/multistaking_test.go
  x/btcstaking/types/errors.go
Labels: backport-to-release/v3.x

#1384 Adjust to code for cascaded slashing
  CHANGELOG.md
  proto/babylon/btcstaking/v1/events.proto
  test/replay/btcstaking_test.go
  test/replay/driver.go
  testutil/datagen/btcstaking.go
  x/btcstaking/keeper/finality_providers.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/types/btc_delegation.go
  x/btcstaking/types/events.go
  x/btcstaking/types/events.pb.go
Labels: backport-to-release/v3.x

#1394 migration of FP data
  CHANGELOG.md
  x/btcstaking/keeper/finality_providers.go
  x/btcstaking/keeper/genesis.go
  x/btcstaking/keeper/migrations.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/migrations/v2/store.go
  x/btcstaking/migrations/v2/store_test.go
  x/btcstkconsumer/keeper/msg_server.go
  x/btcstkconsumer/keeper/msg_server_test.go
  x/btcstkconsumer/types/consumer_register.go
Labels: backport-to-release/v3.x

#1392 chore: e2e bsn rollup rewards
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  test/e2e/btc_rewards_distribution_bsn_rollup_e2e_test.go
  test/e2e/btc_rewards_distribution_e2e_test.go
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  test/e2e/configurer/chain/commands.go
  test/e2e/configurer/chain/commands_btcstaking.go
  test/e2e/configurer/chain/commands_btcstkconsumer.go
  test/e2e/configurer/chain/commands_rollup.go
  test/e2e/configurer/chain/fp.go
  test/e2e/configurer/chain/queries_btcstkconsumer.go
  test/e2e/containers/containers.go
  test/e2e/e2e_test.go
  test/e2e/finality_contract_e2e_test.go
  test/e2e/initialization/config.go
  test/e2e/initialization/export.go
  testutil/datagen/btcstaking.go
  x/btcstkconsumer/client/cli/query.go
  x/btcstkconsumer/module.go
  x/mint/module_test.go
Labels: backport-to-release/v3.x

#1406 feat(btcstkconsumer): Use `collections` for KV store handling.
  CHANGELOG.md
  x/btcstkconsumer/keeper/consumer_registry.go
  x/btcstkconsumer/keeper/genesis.go
  x/btcstkconsumer/keeper/grpc_query.go
  x/btcstkconsumer/keeper/keeper.go
  x/btcstkconsumer/keeper/params.go
  x/btcstkconsumer/types/keys.go
Labels: backport-to-release/v3.x

#1425 Vote ext improvment
  CHANGELOG.md
  testutil/helper/helper.go
  x/checkpointing/prepare/proposal.go
  x/checkpointing/prepare/proposal_test.go
Labels: backport-to-release/v3.x

#1460 imp: add amt change restriction in multi-stk
  CHANGELOG.md
  x/btcstaking/keeper/allowed_transaction_index.go
  x/btcstaking/keeper/allowed_transaction_index_test.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/multistaking_test.go
  x/btcstaking/migrations/v2/store_test.go
Labels: backport-to-release/v3.x
