Repository babylonlabs-io/babylon, pull requests merged in 2025-08, with the labels that each got.

#1463 doc: zone concierge IBC channel doc
  CHANGELOG.md
  docs/ibc-zoneconcierge-setup.md
  x/zoneconcierge/README.md
Labels: backport-to-release/v3.x

#1464 chore: tryfix flaky e2e rewards
  CHANGELOG.md
  test/e2e/btc_rewards_distribution_bsn_rollup_e2e_test.go
  test/e2e/btc_rewards_distribution_e2e_test.go
  test/e2e/btc_rewards_distribution_ibc_callbacks_e2e_test.go
  x/btcstkconsumer/keeper/genesis_test.go
Labels: backport-to-release/v3.x

#1483 remove loging to dockerhub
  .github/workflows/ci.yml
Labels: A:no-changelog, backport-to-release/v3.x

#1474 chore: add incentives query fp current rewards
  CHANGELOG.md
  client/docs/swagger-ui/swagger.yaml
  proto/babylon/incentive/query.proto
  x/incentive/client/cli/query.go
  x/incentive/keeper/grpc_query.go
  x/incentive/keeper/grpc_query_test.go
  x/incentive/types/query.pb.go
  x/incentive/types/query.pb.gw.go
  x/incentive/types/rewards.go
  x/incentive/types/rewards_test.go
Labels: backport-to-release/v3.x, backport-to-release/v2.2.x

#1476 add limit for ibc packet
  CHANGELOG.md
  test/e2e/configurer/current.go
  test/e2e/initialization/chain/main.go
  test/e2e/initialization/config.go
  test/e2e/initialization/init.go
  test/e2e/initialization/init_test.go
  test/e2e/initialization/node.go
  test/replay/driver.go
  test/replay/multistaking_test.go
  test/replay/replayer.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/btc_staking_consumer_events.go
  x/btcstaking/keeper/inclusion_proof.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/types/params.go
Labels: backport-to-release/v3.x

#1500 fix: Proper naming convention for pop docs
  x/btcstaking/docs/proof-of-possesion.md
Labels: A:no-changelog, backport-to-release/v3.x

#1491 fix: restore proofConsumerHeaderInEpoch allocation removed in PR #1387
  CHANGELOG.md
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
Labels: backport-to-release/v3.x

#1514 chore: test get headers to broadcast up k blocks
  x/zoneconcierge/keeper/ibc_packet_btc_headers.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp_test.go
Labels: A:no-changelog

#1485 imp: add bsn chan check on fp creation
  CHANGELOG.md
  app/keepers/keepers.go
  test/e2e/btc_rewards_distribution_ibc_callbacks_e2e_test.go
  test/e2e/btc_staking_e2e_test.go
  test/e2e/configurer/base.go
  test/e2e/configurer/chain/commands_btcstkconsumer.go
  test/e2e/configurer/chain/fp.go
  test/e2e/configurer/chain/queries_ibc.go
  test/e2e/configurer/factory.go
  test/replay/bsn_incentive_test.go
  test/replay/ibc_channel.go
  test/replay/incentive_test.go
  test/replay/multistaking_test.go
  testutil/btcstaking-helper/keeper.go
  testutil/incentives-helper/keeper.go
  testutil/keeper/btcstaking.go
  testutil/keeper/zoneconcierge.go
  testutil/mocks/zc_chan_keeper.go
  x/btcstaking/genesis_test.go
  x/btcstaking/keeper/btc_height_index_test.go
  x/btcstaking/keeper/btc_reorg_test.go
  x/btcstaking/keeper/finality_providers.go
  x/btcstaking/keeper/grpc_query_test.go
  x/btcstaking/keeper/hooks_test.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/keeper/params_test.go
  x/btcstaking/keeper/query_params_test.go
  x/btcstaking/keeper/rewards_test.go
  x/btcstaking/migrations/v2/store_test.go
  x/btcstaking/types/errors.go
  x/btcstaking/types/expected_keepers.go
  x/btcstaking/types/mocked_keepers.go
  x/btcstkconsumer/keeper/consumer_registry.go
  x/btcstkconsumer/types/expected_keepers.go
  x/finality/keeper/msg_server_test.go
  x/finality/keeper/power_dist_change_test.go
  x/zoneconcierge/keeper/channel_keeper.go
  x/zoneconcierge/keeper/genesis.go
  x/zoneconcierge/keeper/ibc_channels.go
  x/zoneconcierge/keeper/ibc_packet_btc_headers.go
  x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
  x/zoneconcierge/keeper/keeper.go
  x/zoneconcierge/types/expected_keepers.go
  x/zoneconcierge/types/mocked_keepers.go
Labels: backport-to-release/v3.x

#1473 chore: e2e test for incentives migration in upgrade v3
  CHANGELOG.md
  app/include_upgrade_e2e.go
  app/include_upgrade_mainnet.go
  app/include_upgrade_testnet.go
  app/upgrades/v3/upgrades.go
  app/upgrades/v3/upgrades_test.go
  contrib/images/Makefile
  proto/babylon/incentive/rewards.proto
  test/e2e/btc_rewards_distribution_e2e_test.go
  test/e2e/btc_rewards_distribution_ibc_callbacks_e2e_test.go
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  test/e2e/configurer/chain/commands_btcstaking.go
  test/e2e/configurer/chain/commands_btcstkconsumer.go
  test/e2e/configurer/chain/queries_btcstaking.go
  test/e2e/configurer/chain/queries_finality.go
  test/e2e/configurer/chain/queries_incentive.go
  test/e2e/configurer/factory.go
  test/e2e/containers/config.go
  test/e2e/govProps/v3.json
  test/e2e/gov_finality_resume.go
  test/e2e/ibc_transfer_e2e_test.go
  test/e2e/software_upgrade_e2e_v3_test.go
  x/incentive/types/rewards.pb.go
Labels: backport-to-release/v3.x

#1521 change log update
  CHANGELOG.md
Labels: A:no-changelog

#1525 chore: remove `SlashedBTCDelegation`
  CHANGELOG.md
  proto/babylon/btcstaking/v1/genesis.proto
  proto/babylon/btcstaking/v1/packet.proto
  test/e2e/btc_rewards_distribution_e2e_test.go
  test/replay/bsn_incentive_test.go
  test/replay/btcstaking_test.go
  test/replay/driver.go
  test/replay/finality_provider_sender.go
  test/replay/scenario_builder.go
  x/btcstaking/keeper/btc_staking_consumer_events.go
  x/btcstaking/keeper/btc_staking_consumer_events_test.go
  x/btcstaking/keeper/finality_providers.go
  x/btcstaking/keeper/keeper_test.go
  x/btcstaking/types/btc_staking_consumer_events.go
  x/btcstaking/types/genesis.go
  x/btcstaking/types/genesis.pb.go
  x/btcstaking/types/genesis_test.go
  x/btcstaking/types/packet.pb.go
  x/finality/keeper/msg_server.go
  x/finality/keeper/msg_server_test.go
  x/finality/types/expected_keepers.go
  x/finality/types/mocked_keepers.go
  x/incentive/keeper/reward_tracker_store_test.go
  x/zoneconcierge/keeper/ibc_packet_btc_staking_consumer_event.go
  x/zoneconcierge/types/expected_keepers.go
  x/zoneconcierge/types/mocked_keepers.go
Labels: backport-to-release/v3.x

#1529 chore: allow zero len coins as fp historical rewards
  CHANGELOG.md
  x/incentive/genesis_test.go
  x/incentive/types/rewards.go
Labels: backport-to-release/v3.x, backport-to-release/v2.2.x

#1536 fix(zoneconcierge): refactor for optimize ibc channel, client related io
  CHANGELOG.md
  test/replay/bsn_incentive_test.go
  test/replay/btcstaking_test.go
  test/replay/driver.go
  test/replay/finality_test.go
  test/replay/incentive_test.go
  test/replay/multistaking_test.go
  test/replay/replayer.go
  testutil/btcstaking-helper/keeper.go
  testutil/datagen/btcstkconsumer.go
  testutil/mocks/zc_chan_keeper.go
  x/btcstaking/keeper/finality_provider_consumer_validation_test.go
  x/btcstaking/keeper/finality_providers.go
  x/btcstaking/keeper/grpc_query_test.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/types/expected_keepers.go
  x/btcstaking/types/mocked_keepers.go
  x/btcstkconsumer/keeper/consumer_registry.go
  x/btcstkconsumer/keeper/consumer_registry_test.go
  x/btcstkconsumer/keeper/msg_server_test.go
  x/btcstkconsumer/types/expected_keepers.go
  x/zoneconcierge/genesis_test.go
  x/zoneconcierge/keeper/channel_keeper.go
  x/zoneconcierge/keeper/channel_keeper_test.go
  x/zoneconcierge/keeper/consumer_registry.go
  x/zoneconcierge/keeper/genesis_test.go
  x/zoneconcierge/keeper/grpc_query_test.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
  x/zoneconcierge/types/expected_keepers.go
  x/zoneconcierge/types/mocked_keepers.go
Labels: backport-to-release/v3.x

#1523 fix: change SigGasConsumer to accepts `ethsecp256k1` as a pubkey
  CHANGELOG.md
  app/ante/ante.go
  app/evm_ante.go
Labels: backport-to-release/v4.x

#1564 doc: zc IBC channel doc revision
  docs/ibc-zoneconcierge-setup.md
Labels: A:no-changelog, backport-to-release/v4.x, backport-to-release/v3.x

#1552 chore: e2e refactory
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  app/include_upgrade_mainnet.go
  crypto/erc2335/erc2335_test.go
  test/e2e/configurer/chain/chain.go
  test/e2e/ibc_transfer_e2e_test.go
  test/e2e/initialization/chain.go
  test/e2e/initialization/config.go
  test/e2e/initialization/node.go
  test/e2e/initialization/util.go
  test/e2ev2/btc_rewards_ibc_test.go
  test/e2ev2/bytecode/README.md
  test/e2ev2/bytecode/finality.wasm
  test/e2ev2/bytecode/finality_contract_version.txt
  test/e2ev2/bytecode/storage_contract.wasm
  test/e2ev2/bytecode/version.txt
  test/e2ev2/ibc_test.go
  test/e2ev2/scripts/copy_finality_contract_local_wasm.sh
  test/e2ev2/scripts/download_finality_contract_release.sh
  test/e2ev2/scripts/hermes_bootstrap.sh
  test/e2ev2/scripts/rly_bootstrap.sh
  test/e2ev2/tmanager/chain.go
  test/e2ev2/tmanager/container.go
  test/e2ev2/tmanager/genesis.go
  test/e2ev2/tmanager/hermes.go
  test/e2ev2/tmanager/manager.go
  test/e2ev2/tmanager/node.go
  test/e2ev2/tmanager/node_queries.go
  test/e2ev2/tmanager/node_txs.go
  test/e2ev2/tmanager/port.go
  test/e2ev2/tmanager/wallet.go
  test/replay/bank.go
  test/replay/bsn_incentive_test.go
  test/replay/incentive.go
  test/replay/replayer.go
  testutil/datagen/epoching.go
  testutil/datagen/zoneconcierge.go
  testutil/events/utils.go
  testutil/keeper/zoneconcierge.go
  wasmbinding/wasm.go
  x/btclightclient/keeper/triggers_test.go
  x/btclightclient/types/genesis_test.go
  x/btcstaking/types/allowlist/multi_staking_allow_list_placeholder.go
  x/btcstaking/types/btc_delegation_test.go
  x/btcstaking/types/genesis_test.go
  x/btcstkconsumer/types/consumer_register_test.go
  x/checkpointing/types/bls_key_test.go
  x/checkpointing/types/checkpoint_test.go
  x/epoching/types/epoching_test.go
  x/incentive/keeper/genesis_test.go
  x/mint/keeper/genesis_test.go
  x/mint/module_test.go
  x/monitor/keeper/genesis_test.go
  x/zoneconcierge/keeper/grpc_query_test.go
  x/zoneconcierge/types/btc_timestamp_test.go
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#1568 feat: wrapper feemarket to exclude refundable gas
  CHANGELOG.md
  app/ante/ante.go
  app/app.go
  x/feemarketwrapper/integration_test.go
  x/feemarketwrapper/module.go
  x/feemarketwrapper/module_test.go
  x/feemarketwrapper/types.go
  x/incentive/keeper/refund_tx_decorator.go
  x/incentive/keeper/refund_tx_decorator_test.go
Labels: backport-to-release/v4.x

#1586 chore: Publish docker images for all release branches
  .github/workflows/publish.yml
Labels: backport-to-release/v2.x, backport-to-release/v4.x, backport-to-release/v3.x

#1571 perf(zc): Optimize bottlenecks by caching redundant store io
  CHANGELOG.md
  x/btclightclient/keeper/cache_test.go
  x/btclightclient/keeper/keeper.go
  x/btclightclient/keeper/keeper_header_cache_test.go
  x/btclightclient/keeper/keeper_test.go
  x/btclightclient/keeper/state.go
  x/btclightclient/module.go
  x/btclightclient/types/header_cache.go
  x/zoneconcierge/keeper/endblocker_bench_test.go
  x/zoneconcierge/keeper/ibc_packet.go
  x/zoneconcierge/keeper/ibc_packet_btc_headers.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp.go
  x/zoneconcierge/keeper/ibc_packet_btc_timestamp_test.go
  x/zoneconcierge/types/expected_keepers.go
  x/zoneconcierge/types/mocked_keepers.go
  x/zoneconcierge/types/packet_cache.go
  x/zoneconcierge/types/packet_cache_test.go
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#1608 fix: `LargestBtcReorg` prefix to follow mainnet
  CHANGELOG.md
  app/upgrades/delete_dup_fp.go
  app/upgrades/v2_3/upgrades.go
  app/upgrades/v3rc3/upgrades.go
  app/upgrades/v3rc3/upgrades_test.go
  x/btcstaking/types/keys.go
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#1596 imp(btcstkconsumer): add finality contract idx
  CHANGELOG.md
  app/upgrades/btcstaking/delete_dup_fp.go
  app/upgrades/btcstaking/delete_dup_fp_test.go
  app/upgrades/btcstaking/testdata/out-fps-mainnet.json
  app/upgrades/btcstaking/testdata/out-fps-testnet.json
  app/upgrades/v2_3/upgrades.go
  app/upgrades/v3rc3/upgrades.go
  app/upgrades/v3rc3/upgrades_test.go
  x/btcstkconsumer/keeper/consumer_registry.go
  x/btcstkconsumer/keeper/keeper.go
  x/btcstkconsumer/keeper/msg_server.go
  x/btcstkconsumer/keeper/msg_server_test.go
  x/btcstkconsumer/types/errors.go
  x/btcstkconsumer/types/keys.go
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#1635 fix: remove duplicated ValidateBasic checks
  CHANGELOG.md
  test/integration/validate_basic_app_test.go
  testutil/helper/helper.go
  x/btclightclient/keeper/msg_server.go
  x/btclightclient/types/msgs.go
  x/finality/keeper/msg_server.go
  x/finality/keeper/msg_server_test.go
Labels: backport-to-release/v4.x, backport-to-release/v3.x
