Repository babylonlabs-io/babylon, pull requests merged in 2025-02, with the labels that each got.

#457 feat: epoching to replace staking msg server
  CHANGELOG.md
  app/ante/ante.go
  app/app.go
  app/app_test.go
  app/keepers/keepers.go
  app/test_helpers.go
  client/client/tx.go
  cmd/babylond/cmd/bls/create_bls_key.go
  cmd/babylond/cmd/genhelpers/bls_add.go
  cmd/babylond/cmd/genhelpers/bls_add_test.go
  cmd/babylond/cmd/genhelpers/bls_create.go
  cmd/babylond/cmd/genhelpers/cmd.go
  cmd/babylond/cmd/genhelpers/collect.go
  cmd/babylond/cmd/genhelpers/gentx.go
  cmd/babylond/cmd/genhelpers/gentx_test.go
  cmd/babylond/cmd/root.go
  cmd/babylond/cmd/testnet.go
  cmd/babylond/cmd/validate_genesis.go
  go.mod
  privval/file.go
  proto/babylon/epoching/v1/epoching.proto
  proto/babylon/epoching/v1/events.proto
  proto/babylon/epoching/v1/tx.proto
  test/e2e/initialization/config.go
  test/e2e/initialization/node.go
  testutil/helper/gen_blocks.go
  testutil/helper/helper.go
  testutil/keeper/epoching.go
  testutil/mocks/checkpointing_expected_keepers.go
  x/checkpointing/keeper/msg_server.go
  x/checkpointing/types/expected_keepers.go
  x/checkpointing/types/genesis.go
  x/epoching/README.md
  x/epoching/client/cli/tx.go
  x/epoching/keeper/drop_validator_msg_decorator.go
  x/epoching/keeper/drop_validator_msg_decorator_test.go
  x/epoching/keeper/epoch_msg_queue.go
  x/epoching/keeper/epoch_msg_queue_test.go
  x/epoching/keeper/keeper.go
  x/epoching/keeper/msg_server.go
  x/epoching/keeper/msg_server_test.go
  x/epoching/keeper/staking_functions.go
  x/epoching/types/epoching.go
  x/epoching/types/epoching.pb.go
  x/epoching/types/errors.go
  x/epoching/types/events.pb.go
  x/epoching/types/msg.go
  x/epoching/types/tx.pb.go
Labels: consensus breaking, api breaking, backport release/v1.x

#473 fix status check from confirmed checkpoint
  CHANGELOG.md
  x/checkpointing/keeper/keeper.go
  x/checkpointing/keeper/keeper_test.go
Labels: consensus breaking, backport release/v1.x

#467 feat: BLS keystore improvement
  CHANGELOG.md
  Makefile
  app/app.go
  app/app_test.go
  app/build_tags.go
  app/encoding.go
  app/include_upgrade_e2e.go
  app/keepers/keepers.go
  app/signer/bls.go
  app/signer/bls_test.go
  app/signer/private.go
  app/signer/types.go
  app/signer/util.go
  app/test_helpers.go
  cmd/babylond/cmd/bls/create_bls_key.go
  cmd/babylond/cmd/cmd_test.go
  cmd/babylond/cmd/create_bls_key.go
  cmd/babylond/cmd/flags.go
  cmd/babylond/cmd/genhelpers/gentx.go
  cmd/babylond/cmd/genhelpers/gentx_test.go
  cmd/babylond/cmd/init.go
  cmd/babylond/cmd/migrate_bls_key.go
  cmd/babylond/cmd/migrate_bls_key_test.go
  cmd/babylond/cmd/root.go
  cmd/babylond/cmd/testnet.go
  cmd/babylond/cmd/testnet_test.go
  cmd/babylond/cmd/validate_genesis_test.go
  contrib/images/Makefile
  crypto/erc2335/erc2335.go
  crypto/erc2335/erc2335_test.go
  go.mod
  go.sum
  privval/file.go
  test/e2e/initialization/config.go
  test/e2e/initialization/export.go
  test/e2e/initialization/node.go
  test/replay/driver.go
  testutil/datagen/btc_blockchain.go
  testutil/datagen/genesiskey.go
  testutil/datagen/init_val.go
  testutil/helper/helper.go
  testutil/keeper/checkpointing.go
  testutil/mocks/bls_signer.go
  testutil/mocks/checkpointing_expected_keepers.go
  testutil/signer/private.go
  x/checkpointing/client/cli/tx_test.go
  x/checkpointing/client/cli/utils.go
  x/checkpointing/genesis_test.go
  x/checkpointing/keeper/bls_signer.go
  x/checkpointing/keeper/keeper.go
  x/checkpointing/keeper/msg_server_test.go
  x/checkpointing/keeper/registration_state.go
  x/checkpointing/types/errors.go
  x/checkpointing/types/expected_keepers.go
  x/checkpointing/types/msgs_test.go
  x/checkpointing/types/pop_test.go
  x/checkpointing/types/types.go
  x/checkpointing/vote_ext.go
  x/checkpointing/vote_ext_test.go
  x/epoching/keeper/staking_functions.go
Labels: backport release/v1.x

#476 chore: bump comet bft to v0.38.17
  CHANGELOG.md
  go.mod
  go.sum
Labels: consensus breaking, backport release/v1.x

#483 Upgrade wasmd / wasmvm
  CHANGELOG.md
  go.mod
  go.sum
Labels: consensus breaking, backport release/v1.x

#491 allow 4 decimal places in slashing rateparamter
  CHANGELOG.md
  app/upgrades/v1/mainnet/btcstaking_params.go
  btcstaking/staking.go
  btcstaking/staking_test.go
  btcstaking/types.go
  btcstaking/types_test.go
  testutil/btcstaking-helper/keeper.go
  x/btcstaking/types/genesis_test.go
  x/btcstaking/types/params.go
  x/btcstaking/types/params_test.go
Labels: consensus breaking, backport release/v1.x

#486 crypto: blinding base mult of nonce
  CHANGELOG.md
  crypto/common/common.go
  crypto/eots/eots.go
  crypto/schnorr-adaptor-signature/sign_utils.go
Labels: backport release/v1.x

#508 pop: move pop constructor functions to datagen/
  CHANGELOG.md
  test/e2e/btc_staking_e2e_test.go
  test/e2e/btc_staking_pre_approval_e2e_test.go
  test/e2e/configurer/chain/commands_btcstaking.go
  testutil/btcstaking-helper/keeper.go
  testutil/datagen/btcstaking.go
  testutil/datagen/pop.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/types/pop.go
  x/btcstaking/types/pop_test.go
  x/btcstaking/types/validate_parsed_message_test.go
Labels: backport release/v1.x

#509 crypto: fix ecdsa malleability
  CHANGELOG.md
  crypto/ecdsa/ecdsa.go
  crypto/ecdsa/ecdsa_test.go
Labels: backport release/v1.x

#505 fix status field in rpc api
  CHANGELOG.md
  x/btcstaking/keeper/btc_consumer_delegations.go
  x/btcstaking/keeper/grpc_query.go
  x/btcstaking/keeper/grpc_query_test.go
Labels: backport release/v1.x

#515 add staker address to the creation event
  CHANGELOG.md
  proto/babylon/btcstaking/v1/events.proto
  proto/buf.lock
  x/btcstaking/types/events.go
  x/btcstaking/types/events.pb.go
Labels: backport release/v1.x

#523 chore: docs: Remove stale docs and diagrams
  .gitignore
  Makefile
  client/README.md
  client/docs/README.md
  client/docs/diagrams/Makefile
  client/docs/diagrams/btc_light_client.png
  client/docs/diagrams/btc_light_client.puml
  client/docs/diagrams/create_raw_checkpoint.png
  client/docs/diagrams/create_raw_checkpoint.puml
  client/docs/diagrams/database_schema.png
  client/docs/diagrams/database_schema.puml
  client/docs/diagrams/submit_checkpoint.png
  client/docs/diagrams/submit_checkpoint.puml
  client/docs/diagrams/validator_registration.png
  client/docs/diagrams/validator_registration.puml
Labels: A:no-changelog

#527 fix: Add bls signer to start command with password options
  CHANGELOG.md
  app/signer/bls.go
  app/signer/bls_test.go
  cmd/babylond/cmd/cmd_test.go
  cmd/babylond/cmd/root.go
Labels: backport release/v1.x

#545 test fix backport
  .github/workflows/backport.yml
Labels: backport-to-fix-bp-test1

#546 init
  .github/workflows/backport.yml
Labels: backport-to-fix-bp-test1

#547 try bp fix 3
  .github/workflows/backport.yml
Labels: backport-to-fix-bp-test1

#554 chore: Improve vote extension logs
  CHANGELOG.md
  x/checkpointing/proposal.go
  x/checkpointing/vote_ext.go
Labels: backport-to-release/v1.x

#563 reject coinbase staking tx
  CHANGELOG.md
  x/btcstaking/keeper/inclusion_proof.go
  x/btcstaking/keeper/inclusion_proof_test.go
Labels: consensus breaking, backport-to-release/v1.x

#567 fix(finality): check for overflow in CommitPubRandList
  CHANGELOG.md
  x/finality/keeper/msg_server.go
  x/finality/keeper/msg_server_test.go
  x/finality/types/errors.go
Labels: consensus breaking, backport-to-release/v1.x

#566 fix(epoching): remove float values in BeforeValidatorSlashed hook
  CHANGELOG.md
  x/epoching/keeper/hooks.go
Labels: backport-to-release/v1.x

#538 Upgrade wasm 2
  CHANGELOG.md
  app/ante/ante.go
  app/app.go
  app/keepers/keepers.go
  app/modules.go
  cmd/babylond/cmd/custom_babylon_config.go
  go.mod
  go.sum
  wasmbinding/grpc_whitelist.go
Labels: consensus breaking

#574 [Backport] Update cosmos sdk (#571)
  go.mod
  go.sum
Labels: consensus breaking, A:no-changelog

#576 Upgrade wasm
  CHANGELOG.md
  app/ante/ante.go
  app/app.go
  app/keepers/keepers.go
  app/modules.go
  cmd/babylond/cmd/custom_babylon_config.go
  go.mod
  go.sum
Labels: consensus breaking

#518 fix: add `btc reorg > k` check in end blocker
  CHANGELOG.md
  app/keepers/keepers.go
  client/docs/swagger-ui/swagger.yaml
  proto/babylon/btclightclient/v1/event.proto
  proto/babylon/btcstaking/v1/btcstaking.proto
  proto/babylon/btcstaking/v1/query.proto
  proto/buf.lock
  x/btccheckpoint/keeper/hooks.go
  x/btclightclient/README.md
  x/btclightclient/keeper/hooks.go
  x/btclightclient/keeper/keeper.go
  x/btclightclient/keeper/triggers.go
  x/btclightclient/keeper/triggers_test.go
  x/btclightclient/keeper/utils_test.go
  x/btclightclient/types/event.pb.go
  x/btclightclient/types/expected_keepers.go
  x/btclightclient/types/hooks.go
  x/btcstaking/abci.go
  x/btcstaking/client/cli/query.go
  x/btcstaking/docs/btc-reorg.md
  x/btcstaking/keeper/btc_reorg.go
  x/btcstaking/keeper/btc_reorg_test.go
  x/btcstaking/keeper/grpc_query.go
  x/btcstaking/keeper/hooks.go
  x/btcstaking/keeper/hooks_test.go
  x/btcstaking/keeper/keeper.go
  x/btcstaking/keeper/msg_server_test.go
  x/btcstaking/types/btcstaking.go
  x/btcstaking/types/btcstaking.pb.go
  x/btcstaking/types/errors.go
  x/btcstaking/types/keys.go
  x/btcstaking/types/query.pb.go
  x/btcstaking/types/query.pb.gw.go
Labels: security, consensus breaking, backport-to-release/v1.x

#466 chore: add test for block send of ubbn and still create btc delegation
  CHANGELOG.md
  test/e2e/btc_staking_e2e_test.go
  test/e2e/configurer/chain/queries.go
  test/e2e/configurer/config/constants.go
  test/e2e/containers/containers.go
  test/e2e/govProps/block-bank-send.json
  test/e2e/govProps/v1.json
Labels: backport-to-release/v1.x

#584 fix: Panic can be triggered in handling liveness
  CHANGELOG.md
  x/finality/keeper/liveness.go
  x/finality/keeper/power_dist_change_test.go
Labels: security, consensus breaking, backport-to-release/v1.x

#592 finality: avoid refunding finality signatures over forks
  CHANGELOG.md
  x/finality/keeper/msg_server.go
Labels: bug, backport-to-release/v1.x

#579 fix: slashed fp inclusion proof
  CHANGELOG.md
  test/replay/driver.go
  testutil/datagen/btcstaking.go
  x/btcstaking/keeper/btc_reorg_test.go
  x/finality/keeper/power_dist_change.go
  x/finality/keeper/power_dist_change_test.go
  x/finality/types/power_table.go
  x/finality/types/power_table_test.go
Labels: security, consensus breaking, backport-to-release/v1.x

#590 chore(incentive): add `DelegationRewards` query
  CHANGELOG.md
  proto/babylon/incentive/query.proto
  x/incentive/client/cli/query.go
  x/incentive/keeper/grpc_query.go
  x/incentive/keeper/grpc_query_test.go
  x/incentive/types/query.pb.go
  x/incentive/types/query.pb.gw.go
Labels: backport-to-release/v1.x

#591 chore: bump ibc-go to v8.6.1
  CHANGELOG.md
  cmd/babylond/cmd/root.go
  go.mod
  go.sum
Labels: consensus breaking, backport-to-release/v1.x

#542 chore(x/incentive): add missing data to genesis
  CHANGELOG.md
  proto/babylon/incentive/genesis.proto
  x/incentive/keeper/genesis.go
  x/incentive/keeper/genesis_test.go
  x/incentive/keeper/keeper.go
  x/incentive/keeper/reward_tracker_store.go
  x/incentive/types/genesis.go
  x/incentive/types/genesis.pb.go
  x/incentive/types/genesis_test.go
  x/incentive/types/rewards.go
Labels: backport-to-release/v1.x
