Repository babylonlabs-io/babylon, pull requests merged in 2025-05, with the labels that each got.

#847 feat: Wire up ibc callbacks
  CHANGELOG.md
  app/keepers/keepers.go
  app/params/config.go
  go.mod
Labels: consensus breaking, backport-to-release/v2.x

#843 chore(x/epoching): add init/export genesis logic
  CHANGELOG.md
  proto/babylon/epoching/v1/genesis.proto
  testutil/datagen/epoching.go
  testutil/datagen/tendermint.go
  testutil/keeper/epoching.go
  wasmbinding/test/custom_query_test.go
  x/epoching/genesis.go
  x/epoching/keeper/epoch_msg_queue.go
  x/epoching/keeper/epoch_slashed_val_set.go
  x/epoching/keeper/epoch_val_set.go
  x/epoching/keeper/epochs.go
  x/epoching/keeper/genesis.go
  x/epoching/keeper/genesis_test.go
  x/epoching/types/epoching.go
  x/epoching/types/epoching_test.go
  x/epoching/types/genesis.go
  x/epoching/types/genesis.pb.go
  x/epoching/types/genesis_test.go
  x/finality/keeper/power_dist_change_test.go
Labels: backport-to-release/v2.x

#860 fix: ensure active fps have signing info after proposal
  CHANGELOG.md
  client/query/client.go
  client/query/epoching.go
  test/replay/driver.go
  test/replay/finality_test.go
  test/replay/scenario_builder.go
  x/finality/keeper/gov.go
  x/finality/keeper/gov_test.go
  x/finality/keeper/power_dist_change.go
Labels: backport-to-release/v2.x, backport-to-release/v1.1.x

#859 chore(x/finality): Update init/export genesis logic
  CHANGELOG.md
  proto/babylon/finality/v1/genesis.proto
  testutil/datagen/finality.go
  x/finality/keeper/genesis.go
  x/finality/keeper/genesis_test.go
  x/finality/types/errors.go
  x/finality/types/finality.go
  x/finality/types/genesis.go
  x/finality/types/genesis.pb.go
  x/finality/types/genesis_test.go
  x/finality/types/power_table.go
  x/finality/types/power_table_test.go
  x/finality/types/signing_info.go
Labels: backport-to-release/v2.x

#857 add v1.1 upgrade data
  app/include_upgrade_mainnet.go
  app/include_upgrade_testnet.go
  app/upgrades/v1_1/upgrades.go
Labels: A:no-changelog, backport-to-release/v2.x, backport-to-release/v1.1.x

#876 imp: add PFM module
  CHANGELOG.md
  app/app.go
  app/keepers/keepers.go
  app/upgrades/v2/upgrades.go
  go.mod
  go.sum
  test/e2e/ibc_transfer_e2e_test.go
Labels: backport-to-release/v2.x

#881 chore(x/mint): update gen logic
  CHANGELOG.md
  app/upgrades/v1/upgrades.go
  cmd/babylond/cmd/genesis.go
  proto/babylon/mint/v1/genesis.proto
  test/e2e/initialization/config.go
  testutil/keeper/account.go
  testutil/keeper/mint.go
  x/mint/keeper/genesis.go
  x/mint/keeper/genesis_test.go
  x/mint/module.go
  x/mint/types/genesis.go
  x/mint/types/genesis.pb.go
  x/mint/types/minter.go
  x/mint/types/minter_test.go
Labels: backport-to-release/v2.x

#884 chore: bump tokenfactory version
  CHANGELOG.md
  go.mod
  go.sum
Labels: backport-to-release/v2.x

#888 chore: ensure release workflow build the released tag
  .github/workflows/release.yml
Labels: backport-to-release/v2.x, backport-to-release/v1.1.x

#883 chore(x/monitor): Add init/export genesis logic
  CHANGELOG.md
  proto/babylon/monitor/v1/genesis.proto
  testutil/keeper/monitor.go
  x/btccheckpoint/keeper/genesis_test.go
  x/monitor/genesis.go
  x/monitor/keeper/genesis.go
  x/monitor/keeper/genesis_test.go
  x/monitor/types/genesis.go
  x/monitor/types/genesis.pb.go
  x/monitor/types/genesis_test.go
Labels: backport-to-release/v2.x

#905 chore: Add ValidateBasic for CommitPubRandList
  CHANGELOG.md
  x/finality/keeper/msg_server.go
  x/finality/types/msg.go
  x/finality/types/msg_test.go
Labels: backport-to-release/v2.x

#906 chore: add bank wrapper for distribution mod account.
  CHANGELOG.md
  app/keepers/keepers.go
  app/params/addr.go
Labels: backport-to-release/v2.x

#909 fix: update tokenfactory params to use `ubbn` as fee denom
  CHANGELOG.md
  app/upgrades/v2/upgrades.go
  test/e2e/software_upgrade_e2e_v2_test.go
Labels: backport-to-release/v2.x

#877 fix: Reward Distribution Calculated at the babylon block to reward BTC
  CHANGELOG.md
  app/upgrades/v2/upgrades.go
  app/upgrades/v2/upgrades_test.go
  proto/babylon/incentive/events.proto
  proto/babylon/incentive/genesis.proto
  test/e2e/btc_staking_e2e_test.go
  test/e2e/gov_finality_resume.go
  test/replay/bank.go
  test/replay/driver.go
  test/replay/incentive.go
  test/replay/incentive_test.go
  test/replay/scenario_builder.go
  testutil/btcstaking-helper/keeper.go
  x/finality/keeper/msg_server_test.go
  x/finality/keeper/power_dist_change.go
  x/finality/types/expected_keepers.go
  x/finality/types/mocked_keepers.go
  x/incentive/keeper/btc_staking_gauge.go
  x/incentive/keeper/btc_staking_gauge_test.go
  x/incentive/keeper/genesis.go
  x/incentive/keeper/genesis_test.go
  x/incentive/keeper/keeper.go
  x/incentive/keeper/reward_tracker.go
  x/incentive/keeper/reward_tracker_events.go
  x/incentive/keeper/reward_tracker_events_test.go
  x/incentive/keeper/reward_tracker_store_test.go
  x/incentive/keeper/reward_tracker_test.go
  x/incentive/types/events.pb.go
  x/incentive/types/genesis.go
  x/incentive/types/genesis.pb.go
  x/incentive/types/genesis_test.go
  x/incentive/types/keys.go
  x/incentive/types/rewards.go
Labels: backport-to-release/v2.x

#904 chore: update docker_pipeline to v0.13.2
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: backport-to-release/v1.x, backport-to-release/v2.x

#913 chore(x/ibc-fee): remove deprecated mod
  CHANGELOG.md
  app/app.go
  app/app_test.go
  app/keepers/keepers.go
  app/upgrades/v2/upgrades.go
Labels: backport-to-release/v2.x

#902 chore: wire up rate-limiter
  CHANGELOG.md
  app/app.go
  app/keepers/keepers.go
  app/upgrades/v2/upgrades.go
  app/upgrades/v2/upgrades_test.go
  go.mod
  go.sum
  test/e2e/configurer/chain/queries.go
  test/e2e/ibc_transfer_e2e_test.go
  test/e2e/ica_e2e_test.go
  test/e2e/initialization/config.go
Labels: backport-to-release/v2.x

#918 [Backport] Changelog 1.1
  CHANGELOG.md
Labels: backport-to-release/v2.x

#935 chore(ci): add release/v4.x for docker publish workflow
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: backport-to-release/v4.x

#944 feat(btcstaking,btcstkconsumer): Add max_multi_staked_fps validation and single FP per consumer constraint
  CHANGELOG.md
  client/docs/swagger-ui/swagger.yaml
  proto/babylon/btcstkconsumer/v1/btcstkconsumer.proto
  proto/babylon/btcstkconsumer/v1/query.proto
  proto/babylon/btcstkconsumer/v1/tx.proto
  testutil/datagen/btcstkconsumer.go
  x/btcstaking/keeper/btc_delegations.go
  x/btcstaking/keeper/msg_server.go
  x/btcstaking/keeper/restaking_test.go
  x/btcstaking/types/errors.go
  x/btcstaking/types/expected_keepers.go
  x/btcstaking/types/mocked_keepers.go
  x/btcstkconsumer/client/cli/tx.go
  x/btcstkconsumer/keeper/consumer_registry.go
  x/btcstkconsumer/keeper/consumer_registry_test.go
  x/btcstkconsumer/keeper/finality_provider_registry_test.go
  x/btcstkconsumer/keeper/grpc_query_test.go
  x/btcstkconsumer/keeper/msg_server.go
  x/btcstkconsumer/keeper/msg_server_test.go
  x/btcstkconsumer/types/btcstkconsumer.pb.go
  x/btcstkconsumer/types/consumer_register.go
  x/btcstkconsumer/types/consumer_register_test.go
  x/btcstkconsumer/types/errors.go
  x/btcstkconsumer/types/genesis_test.go
  x/btcstkconsumer/types/query.pb.go
  x/btcstkconsumer/types/tx.pb.go
Labels: backport-to-release/v4.x

#943 chore: adds consumer event and consumer_id to fp event
  CHANGELOG.md
  proto/babylon/btcstaking/v1/events.proto
  proto/babylon/btcstkconsumer/v1/events.proto
  x/btcstaking/types/events.go
  x/btcstaking/types/events.pb.go
  x/btcstkconsumer/keeper/msg_server.go
  x/btcstkconsumer/types/events.go
  x/btcstkconsumer/types/events.pb.go
Labels: backport-to-release/v4.x

#947 chore: improve signing info update upon fp activated
  CHANGELOG.md
  go.sum
  x/finality/keeper/liveness.go
  x/finality/keeper/liveness_test.go
  x/finality/keeper/power_dist_change.go
Labels: consensus breaking

#955 ci(Mergify): configuration update
  .mergify.yml
  CHANGELOG.md
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#969 imp(btcstk): add ValidateBasic to MsgSelectiveSlashingEvidence
  CHANGELOG.md
  x/btcstaking/types/create_delegation_parser.go
  x/btcstaking/types/msg.go
  x/btcstaking/types/msg_test.go
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#977 imp: update ValidateBasic in x/finality msgs
  CHANGELOG.md
  x/finality/keeper/msg_server.go
  x/finality/keeper/msg_server_test.go
  x/finality/types/errors.go
  x/finality/types/msg.go
  x/finality/types/msg_test.go
Labels: backport-to-release/v4.x, backport-to-release/v3.x

#981 chore: set default daily limit to 10%
  CHANGELOG.md
  app/upgrades/v2/upgrades.go
Labels: backport-to-release/v2.x

#998 fix: changlog duplicate and add v2.0.0-rc.0
  CHANGELOG.md
Labels: backport-to-release/v2.x

#993 chore: Remove async-icq module
  CHANGELOG.md
  app/app.go
  app/app_test.go
  app/include_upgrade_mainnet.go
  app/include_upgrade_testnet.go
  app/keepers/keepers.go
  app/upgrades/v2/upgrades.go
  app/upgrades/v2/upgrades_test.go
  app/upgrades/v2rc1/testnet/upgrade.go
  go.mod
  go.sum
Labels: backport-to-release/v2.x
